[package]
name = "lazycop"
version = "0.1.0"
authors = ["Michael Rawson <michael@rawsons.uk>"]
edition = "2018"

[dependencies]
fnv = "1.0"
smallvec = "1.2"
tptp = "0.14"

[profile.release]
lto = "fat"
panic = "abort"
