[package]
name = "lazycop"
version = "0.1.0"
authors = ["Michael Rawson <michael@rawsons.uk>"]
edition = "2018"
license = "MIT"

[dependencies]
fnv = "1.0"
num_cpus = "1.13"
parking_lot = "0.10"
tptp = "0.23"

[profile.release]
panic = "abort"
