[package]
name = "lazycop"
version = "0.1.0"
authors = ["Michael Rawson <michael@rawsons.uk>"]
edition = "2018"

[dependencies]
fnv = "1.0"
tptp = "0.23"

[profile.release]
debug = true
panic = "abort"
