#!/bin/sh

form=`grep "^% SPC *: [A-Z0-9_]*$" $1 | sed 's/% SPC *: //' | cut -d '_' -f 1`
if test -z $form || test $form = "CNF" || test $form = "FOF"
then
	exec ./vampire -t 0 --mode clausify $1 -updr off -nm 2 -erd input_only -icip on | ./lazycop
else
	echo "% SZS status Inappropriate"
	exit 1
fi
