#!/bin/sh

form=`grep -m 1 "^% SPC *: [A-Z0-9_]*$" $1 | sed 's/% SPC *: //' | cut -d '_' -f 1`
if test -z $form || test $form = "CNF" || test $form = "FOF"
then
	exec ./lazycop $1
else
	echo "% SZS status Inappropriate"
	exit 1
fi
