[package]
name = "lazycop"
version = "0.1.0"
authors = ["Michael Rawson <michael@rawsons.uk>"]
edition = "2018"
license = "MIT"

[dependencies.lazy]
path = "../lazy"

[dependencies]
crossbeam-utils = "0.7"
num_cpus = "1.13"
parking_lot = "0.10"
